/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyListener;
import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author InSearchOfIncredible
 */
public class datakontrak extends javax.swing.JFrame {

    /**
     * Creates new form datakontrak
     */
    public datakontrak() {
        initComponents();
        this.setLocationRelativeTo(this);
        tb_kontrak.changeSelection(0, 0, true, false);
    }

    public int getSelectedRow() {
        return tb_kontrak.getSelectedRow();
    }

    public void setTable(DefaultTableModel table) {
        this.tb_kontrak.setModel(table);
    }

    public JTable getTableKontrak() {
        return tb_kontrak;
    }

    public String getValueAt(int baris, int kolom) {
        return tb_kontrak.getValueAt(baris, kolom).toString();
    }

    public String getId() {
        return id.getText();
    }

    public void setId(String id) {
        this.id.setText(id);
    }

    public void getLuas(KeyListener a) {
        luas.addKeyListener(a);
    }

    public JTextField getLuas() {
        return luas;
    }

    public JTextField getBibit() {
        return bibit;
    }

    public JTextField getPupuk() {
        return pupuk;
    }

    public JComboBox<String> getPetani() {
        return petani;
    }

    public void setPetani(String[] petani) {
        for (String a : petani) {
            this.petani.addItem(a);
        }
    }

//    
//    public void setPetani(String isi) {
//        this.petani.setText(isi);
//    }
//
//    public void setLuas(String isi) {
//        this.luas.setText(isi);
//    }
    public void setBibit(String bibit) {
        this.bibit.setText(bibit);
    }

    public void setLuas(String luas) {
        this.luas.setText(luas);
    }

    public void setPupuk(String pupuk) {
        this.pupuk.setText(pupuk);
    }

    public void text(boolean status) {
        this.petani.setEnabled(status);
        this.luas.setEnabled(status);
        this.bibit.setEnabled(status);
        this.pupuk.setEnabled(status);
    }

    public void button(boolean status) {
        this.btn_save.setEnabled(status);
        this.btn_delete.setEnabled(status);
        this.btn_back.setEnabled(status);
    }

    public void addSaveListener(ActionListener e) {
        this.btn_save.addActionListener(e);
    }

    public void addDeleteListener(ActionListener e) {
        this.btn_delete.addActionListener(e);
    }

    public void addBackListener(ActionListener e) {
        this.btn_back.addActionListener(e);
    }

    public void buttonsave(boolean status) {
        this.btn_save.setEnabled(status);
    }

    public void buttonback(boolean status) {
        this.btn_back.setEnabled(status);
    }

    public void buttondelete(boolean status) {
        this.btn_delete.setEnabled(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        petani = new javax.swing.JComboBox<>();
        luas = new javax.swing.JTextField();
        bibit = new javax.swing.JTextField();
        pupuk = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_kontrak = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        petani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        petani.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        petani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petaniActionPerformed(evt);
            }
        });
        getContentPane().add(petani, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 170, 50));

        luas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(luas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 170, 50));

        bibit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bibit.setEnabled(false);
        getContentPane().add(bibit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 170, 50));

        pupuk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pupuk.setEnabled(false);
        getContentPane().add(pupuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 170, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kg");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 40, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kg");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 40, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ha");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 40, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID    :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 80, 50));

        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar3/save.png"))); // NOI18N
        btn_save.setBorder(null);
        btn_save.setBorderPainted(false);
        btn_save.setContentAreaFilled(false);
        getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 300, 100, 40));

        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar3/hapus.png"))); // NOI18N
        btn_delete.setBorder(null);
        btn_delete.setBorderPainted(false);
        btn_delete.setContentAreaFilled(false);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 300, 100, 40));

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar3/keluar.png"))); // NOI18N
        btn_back.setBorder(null);
        btn_back.setBorderPainted(false);
        btn_back.setContentAreaFilled(false);
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 580, 170, 60));

        tb_kontrak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_kontrak);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 640, 240));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Data Kontrak");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 320, 90));

        id.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 70, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/data K.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Black Diamonds Personal Use", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Kontrak");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 340, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/data K.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void petaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petaniActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datakontrak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datakontrak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datakontrak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datakontrak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datakontrak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bibit;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField luas;
    private javax.swing.JComboBox<String> petani;
    private javax.swing.JTextField pupuk;
    private javax.swing.JTable tb_kontrak;
    // End of variables declaration//GEN-END:variables
}
