/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author FAZA
 */
public class DetailOutletView extends javax.swing.JFrame {

    /**
     * Creates new form detailOutlet
     */
    public DetailOutletView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKembali = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabelIdOutlet = new javax.swing.JLabel();
        jLabelNamaOutlet = new javax.swing.JLabel();
        jLabelAlamatOutlet = new javax.swing.JLabel();
        jLabelAdminOutlet = new javax.swing.JLabel();
        Frame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnKembali1.png"))); // NOI18N
        btnKembali.setBorder(null);
        btnKembali.setBorderPainted(false);
        btnKembali.setContentAreaFilled(false);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 140, 40));

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnUpdate1.png"))); // NOI18N
        btnUpdate.setBorder(null);
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 140, -1));

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnHapus.png"))); // NOI18N
        btnHapus.setBorder(null);
        btnHapus.setContentAreaFilled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 140, -1));

        jLabelIdOutlet.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabelIdOutlet.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelIdOutlet, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 140, 30));

        jLabelNamaOutlet.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabelNamaOutlet.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelNamaOutlet, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 220, 30));

        jLabelAlamatOutlet.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabelAlamatOutlet.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelAlamatOutlet, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 300, 30));

        jLabelAdminOutlet.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabelAdminOutlet.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelAdminOutlet, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 450, 30));

        Frame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/detailOutlet.png"))); // NOI18N
        getContentPane().add(Frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new TambahOutletView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailOutletView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailOutletView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailOutletView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailOutletView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailOutletView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Frame;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabelAdminOutlet;
    private javax.swing.JLabel jLabelAlamatOutlet;
    private javax.swing.JLabel jLabelIdOutlet;
    private javax.swing.JLabel jLabelNamaOutlet;
    // End of variables declaration//GEN-END:variables
}
