package view;

import java.awt.event.ActionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author World
 */
public class HomeManagerView extends javax.swing.JFrame {

    /**
     * Creates new form HomeManajer
     */
    public HomeManagerView() {
        initComponents();
    }
    
    public void admin(ActionListener a){
       this.btnAdmin.addActionListener(a);
    }
    
    public void outlet(ActionListener a){
        this.btnOutlet.addActionListener(a);
    }
    public void logout(ActionListener a){
        this.btnLogout.addActionListener(a);
    }
    
    public void rekapManager(ActionListener a){
        this.btnRekapPenjualanManajer.addActionListener(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRekapPenjualanManajer = new javax.swing.JButton();
        btnOutlet = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRekapPenjualanManajer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnRekap.png"))); // NOI18N
        btnRekapPenjualanManajer.setBorder(null);
        btnRekapPenjualanManajer.setBorderPainted(false);
        btnRekapPenjualanManajer.setContentAreaFilled(false);
        btnRekapPenjualanManajer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRekapPenjualanManajerMouseClicked(evt);
            }
        });
        btnRekapPenjualanManajer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRekapPenjualanManajerActionPerformed(evt);
            }
        });
        getContentPane().add(btnRekapPenjualanManajer, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 280, 50));

        btnOutlet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnOutlet.png"))); // NOI18N
        btnOutlet.setBorder(null);
        btnOutlet.setContentAreaFilled(false);
        btnOutlet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutletActionPerformed(evt);
            }
        });
        getContentPane().add(btnOutlet, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 280, 50));

        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnUser.png"))); // NOI18N
        btnAdmin.setBorder(null);
        btnAdmin.setContentAreaFilled(false);
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 280, 50));

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnLogOut.png"))); // NOI18N
        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, 280, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HOME.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRekapPenjualanManajerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRekapPenjualanManajerActionPerformed
//    new rekapPenjualanManager().setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_btnRekapPenjualanManajerActionPerformed
                    
    private void btnRekapPenjualanManajerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRekapPenjualanManajerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRekapPenjualanManajerMouseClicked

    private void btnOutletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutletActionPerformed
//        new daftarOutlet().setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_btnOutletActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
//        new daftarAdmin().setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_btnAdminActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOutlet;
    private javax.swing.JButton btnRekapPenjualanManajer;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

  

   
}
