/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Vin
 */
public class PakarKualitas extends javax.swing.JFrame {

    /**
     * Creates new form PakarKualitas
     */
    public PakarKualitas() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public JComboBox<String> getPetani() {
        return petani;
    }

    public void setComboPetani(String[] comboPetani) {
        for (String a : comboPetani) {
            this.petani.addItem(a);
        }
    }

    public JComboBox<String> getVarietas() {
        return varietas;
    }

    public void setComboVarietas(String[] comboVarietas) {
        for (String a : comboVarietas) {
            this.varietas.addItem(a);
        }
    }

    public JComboBox<String> getMatang() {
        return matang;
    }

    public void setComboMatang(String[] comboMatang) {
        for (String a : comboMatang) {
            this.matang.addItem(a);
        }
    }

    public JComboBox<String> getBobot() {
        return bobot;
    }

    public void setComboBobot(String[] comboBobot) {
        for (String a : comboBobot) {
            this.bobot.addItem(a);
        }
    }

    public JComboBox<String> getCacat() {
        return cacat;
    }

    public void setComboCacat(String[] comboCacat) {
        for (String a : comboCacat) {
            this.cacat.addItem(a);
        }
    }

    public void check(ItemListener a) {
        this.petani.addItemListener(a);
    }

    public void addCekListener(ActionListener listener) {
        btn_cek.addActionListener(listener);
    }

    public void backListener(ActionListener listener) {
        btn_kembali.addActionListener(listener);
    }

    public JTextField getLuas(String string) {
        return luas;
    }

    public JTextArea getTindakan(String string) {
        return tindakan;
    }

    public void setTindakan(String text) {
        tindakan.setText(text);
    }

    public void Message(String pesan) {
        JOptionPane.showMessageDialog(this, pesan);
    }

    public void setLuas(String text) {
        luas.setText(text);
    }

    public JTextField getMutu(String string) {
        return kualitas;
    }

    public void setMutu(String text) {
        kualitas.setText(text);
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        luas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        varietas = new javax.swing.JComboBox<>();
        matang = new javax.swing.JComboBox<>();
        bobot = new javax.swing.JComboBox<>();
        cacat = new javax.swing.JComboBox<>();
        btn_cek = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        kualitas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tindakan = new javax.swing.JTextArea();
        btn_kembali = new javax.swing.JButton();
        petani = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pakar Kualitas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Petani         :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 128, 27));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Luas           :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 128, 29));

        luas.setEditable(false);
        luas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(luas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 114, 29));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kriteria Varietas       :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 371, 25));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kriteria Kematangan :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 371, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Kriteria Bobot         :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 371, 28));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kriteria Cacat          :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 371, 29));

        varietas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        varietas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        getContentPane().add(varietas, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 239, 27));

        matang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        matang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        getContentPane().add(matang, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 239, 29));

        bobot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bobot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        getContentPane().add(bobot, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 239, 28));

        cacat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cacat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        getContentPane().add(cacat, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 239, 29));

        btn_cek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar3/cek2.png"))); // NOI18N
        btn_cek.setBorder(null);
        btn_cek.setBorderPainted(false);
        btn_cek.setContentAreaFilled(false);
        btn_cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cekActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cek, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, 99, 34));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kualitas     :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 128, 31));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tindakan   :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 128, 28));

        kualitas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(kualitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 230, 31));

        tindakan.setColumns(20);
        tindakan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tindakan.setRows(5);
        jScrollPane1.setViewportView(tindakan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 526, 76));

        btn_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar3/keluar.png"))); // NOI18N
        btn_kembali.setBorder(null);
        btn_kembali.setBorderPainted(false);
        btn_kembali.setContentAreaFilled(false);
        getContentPane().add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 560, 180, 40));

        petani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        petani.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        petani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petaniActionPerformed(evt);
            }
        });
        getContentPane().add(petani, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 114, 27));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar3/backgrond.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cekActionPerformed

    private void petaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petaniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PakarKualitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PakarKualitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PakarKualitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PakarKualitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PakarKualitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bobot;
    private javax.swing.JButton btn_cek;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JComboBox<String> cacat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kualitas;
    private javax.swing.JTextField luas;
    private javax.swing.JComboBox<String> matang;
    private javax.swing.JComboBox<String> petani;
    private javax.swing.JTextArea tindakan;
    private javax.swing.JComboBox<String> varietas;
    // End of variables declaration//GEN-END:variables
}
