/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import model.Produk;

/**
 *
 * @author World
 */
public class PemesananView extends javax.swing.JFrame {

    private Object[] header = {"ID Produk", "Nama Product", "Harga", "qty"};
    DefaultTableModel tableModel = new DefaultTableModel(null, header);

    public PemesananView() {
        initComponents();
        tabelTambahPesanan.setModel(tableModel);
    }
    
    public DefaultTableModel getModel() {
        return this.tableModel;
    }
    
    public double getSelectedHarga() {
        return Double.parseDouble(tabelTambahPesanan.getValueAt(getRow(), 2).toString());
    }

    public double getSelectedQty() {
        return Double.parseDouble(tabelTambahPesanan.getValueAt(getRow(), 3).toString());
    }
    
    public void plusTotal(double tot) {
        double totSkg = Double.parseDouble(txtTotalBiaya.getText());
        double total = totSkg + tot;
        txtTotalBiaya.setText(total + "");
    }

    public void minTotal(double tot) {
        double totSkg = Double.parseDouble(txtTotalBiaya.getText());
        double total = totSkg - tot;
        txtTotalBiaya.setText(total + "");
    }
    
    public int getRow(){
        return tabelTambahPesanan.getSelectedRow();
    }
    
    public int getProdukSelected(){
        return cbxProduk.getSelectedIndex();
    }
    
    public int getJumlah(){
        return Integer.parseInt(txtJumlah.getText());
    }

    public void addItem(String namaProduk, String idProduk, int qty, double harga) {
        int check = check(idProduk);
        if (check == -1) {
            String kolom[] = {
                idProduk,
                namaProduk,
                harga + "",
                qty + "",};
            tableModel.addRow(kolom);
        } else {
            int qtyBefore = Integer.parseInt(tabelTambahPesanan.getValueAt(check, 3).toString());
            tableModel.setValueAt((qty + qtyBefore) + "", check, 3);
        }
    }

    public int check(String idProduk) {
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            if (idProduk.equals(tableModel.getValueAt(i, 0))) {
                return i;
            }
        }
        return -1;
    }

    public void hapusItem(int row) {
        tableModel.removeRow(row);
    }

    public String getNamaPemesan() {
        return txtNamaPemesan.getText();
    }

    public void setNamaPemesan(String isi) {
        this.txtNamaPemesan.setText(isi);
    }

    public void setJumlah(String isi) {
        this.txtJumlah.setText(isi);
    }

    public String getListJenis() {
        return (String) cbxProduk.getSelectedItem();
    }

    public void setListJenis(String[] listJenis) {
        for (String a : listJenis) {
            this.cbxProduk.addItem(a);
        }
    }

    public void btnKembaliListener(ActionListener a) {
        this.btnKembali.addActionListener(a);
    }

    public void setTabel(DefaultTableModel tabel) {
        this.tabelTambahPesanan.setModel(tabel);
    }

    public void btnTambahListener(ActionListener a) {
        this.btnTambah.addActionListener(a);
    }

    public void btnHapusListener(ActionListener a) {
        this.btnHapus.addActionListener(a);
    }

    public void btnBayarSaveListener(ActionListener a) {
        this.btnBayar.addActionListener(a);
    }
    
    public int getSelectedRow() {
        return tabelTambahPesanan.getSelectedRow();
    }

    public String getValueAt(int baris, int kolom) {
        return (String) this.tabelTambahPesanan.getValueAt(baris, kolom);
    }

    public void addProdukList(ArrayList<Produk> listProduk) {
        System.out.println("test list produk");
        DefaultComboBoxModel<String> mdl = new DefaultComboBoxModel<>();
        for (int i = 0; i < listProduk.size(); i++) {
            mdl.addElement(listProduk.get(i).getNamaProduk());
        }
        cbxProduk.setModel(mdl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKembali = new javax.swing.JButton();
        txtNamaPemesan = new javax.swing.JTextField();
        cbxProduk = new javax.swing.JComboBox<>();
        txtJumlah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTambahPesanan = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        txtBayar = new javax.swing.JTextField();
        txtTotalBiaya = new javax.swing.JTextField();
        txtKembalian = new javax.swing.JTextField();
        btnBayar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnKembali.png"))); // NOI18N
        btnKembali.setBorder(null);
        btnKembali.setBorderPainted(false);
        btnKembali.setContentAreaFilled(false);
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 670, -1, -1));

        txtNamaPemesan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNamaPemesan.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(txtNamaPemesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 180, 30));

        getContentPane().add(cbxProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 220, 30));

        txtJumlah.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtJumlah.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(txtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 60, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tabelTambahPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelTambahPesanan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 750, 520));

        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnTambah.png"))); // NOI18N
        btnTambah.setBorder(null);
        btnTambah.setBorderPainted(false);
        btnTambah.setContentAreaFilled(false);
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, 50));

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnHapus.png"))); // NOI18N
        btnHapus.setBorder(null);
        btnHapus.setBorderPainted(false);
        btnHapus.setContentAreaFilled(false);
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, 50));

        txtBayar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBayar.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(txtBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 180, 30));

        txtTotalBiaya.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotalBiaya.setForeground(new java.awt.Color(153, 0, 0));
        txtTotalBiaya.setText("0");
        getContentPane().add(txtTotalBiaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 180, 30));

        txtKembalian.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtKembalian.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(txtKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 180, 50));

        btnBayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnBayar.png"))); // NOI18N
        btnBayar.setBorder(null);
        btnBayar.setBorderPainted(false);
        btnBayar.setContentAreaFilled(false);
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 290, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PEMESANAN.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBayarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbxProduk;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelTambahPesanan;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtNamaPemesan;
    private javax.swing.JTextField txtTotalBiaya;
    // End of variables declaration//GEN-END:variables
}
