/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author InSearchOfIncredible
 */
public class Pemupukan extends javax.swing.JFrame {

    /**
     * Creates new form spkPupuk
     */
    public Pemupukan() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public void addCekListener(ActionListener listener) {
        btn_cek.addActionListener(listener);
    }

    public void backListener(ActionListener listener) {
        btn_kembali.addActionListener(listener);
    }

    public JLabel getPetani() {
        return petani;
    }

    public JLabel getPupuk() {
        return pupuk;
    }

    public JTextArea getAnalisa(String string) {
        return analisa;
    }

    public void setAnalisa(String text) {
        analisa.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        analisa = new javax.swing.JTextArea();
        btn_cek = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();
        petani = new javax.swing.JLabel();
        pupuk = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        analisa.setColumns(20);
        analisa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        analisa.setRows(5);
        jScrollPane1.setViewportView(analisa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 550, 200));

        btn_cek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar3/cek2.png"))); // NOI18N
        btn_cek.setBorder(null);
        btn_cek.setBorderPainted(false);
        btn_cek.setContentAreaFilled(false);
        getContentPane().add(btn_cek, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 300, 90, 40));

        btn_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar3/keluar.png"))); // NOI18N
        btn_kembali.setBorder(null);
        btn_kembali.setBorderPainted(false);
        btn_kembali.setContentAreaFilled(false);
        btn_kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 590, 170, 50));

        petani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        petani.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(petani, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 210, 40));

        pupuk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pupuk.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pupuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 240, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pemupukan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 280, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/spk pupuk.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemupukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemupukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemupukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemupukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pemupukan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea analisa;
    private javax.swing.JButton btn_cek;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel petani;
    private javax.swing.JLabel pupuk;
    // End of variables declaration//GEN-END:variables
}
