/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author World
 */
public class TambahAkunView extends javax.swing.JFrame {

    /**
     * Creates new form v_tambahMenejer
     */
    public TambahAkunView() {
        initComponents();
    }

    public String getIdAkun() {
        return txtId.getText();
    }

    public void setIdAkun(String isi) {
        this.txtId.setText(isi);
    }

    public String getUsername() {
        return txtUsername.getText();
    }

    public void setUsername(String isi) {
        this.txtUsername.setText(isi);
    }

    public String getPassword() {
        return txtPassword.getText();
    }

    public void setPassword(String isi) {
        this.txtPassword.setText(isi);
    }

    public String getAlamat() {
        return txtAlamat.getText();
    }

    public void setAlamat(String isi) {
        this.txtAlamat.setText(isi);
    }

    public String getLevel() {
        return txtLevel.getText();
    }

    public void setLevel(String isi) {
        this.txtLevel.setText(isi);
    }   
    
    

    public void btnTambah(boolean status) {
        this.btnTambah.setEnabled(status);
    }

    public void btnEdit(boolean status) {
        this.btnEdit.setEnabled(status);
    }

    public void btnPilihListener(ActionListener a) {
        this.btnPilih.addActionListener(a);
    }

    public void btnEditListener(ActionListener a) {
        this.btnEdit.addActionListener(a);
    }

    public void btnTambahListener(ActionListener a) {
        this.btnTambah.addActionListener(a);
    }

    public void btnKembaliListener(ActionListener a) {
        this.btnKembali.addActionListener(a);
    }

    public void setTabel(DefaultTableModel tabel) {
        this.tabelTambahMenejer.setModel(tabel);
    }

    public int getSelectedRow() {
        return tabelTambahMenejer.getSelectedRow();
    }

    public String getValueAt(int baris, int kolom) {
        return (String) this.tabelTambahMenejer.getValueAt(baris, kolom);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnPilih = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTambahMenejer = new javax.swing.JTable();
        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtId = new javax.swing.JLabel();
        txtLevel = new javax.swing.JTextField();
        FRAME = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnTambah.png"))); // NOI18N
        btnTambah.setBorder(null);
        btnTambah.setBorderPainted(false);
        btnTambah.setContentAreaFilled(false);
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnEdit.png"))); // NOI18N
        btnEdit.setBorder(null);
        btnEdit.setBorderPainted(false);
        btnEdit.setContentAreaFilled(false);
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        btnPilih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnPilih.png"))); // NOI18N
        btnPilih.setBorder(null);
        btnPilih.setBorderPainted(false);
        btnPilih.setContentAreaFilled(false);
        getContentPane().add(btnPilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, -1));

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnKembali.png"))); // NOI18N
        btnKembali.setBorder(null);
        btnKembali.setBorderPainted(false);
        btnKembali.setContentAreaFilled(false);
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 650, -1, -1));

        tabelTambahMenejer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelTambahMenejer);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 710, 320));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 240, 30));

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 240, 30));

        txtAlamat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAlamat.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 240, 30));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 10, 10));

        txtLevel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLevel.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(txtLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 240, 30));

        FRAME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/USER.png"))); // NOI18N
        getContentPane().add(FRAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahAkunView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahAkunView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahAkunView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahAkunView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahAkunView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FRAME;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnPilih;
    private javax.swing.JButton btnTambah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelTambahMenejer;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JLabel txtId;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
